import dotenv from "dotenv";
import { TicketCategory, TicketPriority, TicketStatus } from "@prisma/client";
import prisma from "../src/prisma";

dotenv.config();

interface TicketSeedData {
  subject: string;
  body: string;
  senderName: string;
  senderEmail: string;
  category: TicketCategory | null;
  priority: TicketPriority;
  status: TicketStatus;
  createdAt: Date;
}

const rawTickets: Omit<TicketSeedData, "createdAt">[] = [
  // 1-25: Technical Questions
  {
    subject: "React 19: TypeError: Cannot read properties of undefined (reading 'call')",
    body: "Hi Mosh, when running the Vite dev server in Section 3 Lesson 12, React throws this error during module federation. I tried updating to React 19.0.2 but the error persists.",
    senderName: "Marcus Vance",
    senderEmail: "marcus.vance@gmail.com",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Docker: Container exits immediately with code 137 (OOM killed)",
    body: "My PostgreSQL docker container in lesson 8 exits after running migrations. My machine has 16GB RAM. Is there a memory limit flag I should pass in docker-compose.yml?",
    senderName: "Sophia Rodriguez",
    senderEmail: "sophia.rod@outlook.com",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Prisma migration failing: P3006 Migration engine exited with code 1",
    body: "When executing `npx prisma migrate dev`, it fails complaining that shadow database cannot be created because user lacks CREATEDB permission on RDS Postgres.",
    senderName: "Alexander Wright",
    senderEmail: "alex.wright@techstart.io",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Tailwind CSS v4: @apply directive not working in custom component classes",
    body: "After upgrading to Tailwind CSS v4 in the React project, my @apply utilities in globals.css are throwing unknown at-rule warnings and CSS is not generating.",
    senderName: "Elena Rostova",
    senderEmail: "elena.rostova@proton.me",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "TypeScript error TS2322: Type 'null' is not assignable to type 'string'",
    body: "In chapter 4 on generic constraints, strictNullChecks causes an error when defining optional user fields. How do I properly type a nullable fallback in TypeScript 5.7?",
    senderName: "David Kim",
    senderEmail: "dkim.dev@gmail.com",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Next.js App Router: Static page not revalidating on tag invalidation",
    body: "I am calling revalidateTag('products') inside a Server Action, but the products catalogue page still serves the stale cache until a hard reload.",
    senderName: "Chloe Dupont",
    senderEmail: "chloe.dupont@orange.fr",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Node.js memory leak during high-concurrency websocket connections",
    body: "Following the real-time chat module, the process heap keeps climbing when testing with 500 concurrent connections using Autocannon. Where should listeners be detached?",
    senderName: "Liam O'Connor",
    senderEmail: "liam.oc@dublin-tech.ie",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Express JWT Auth: Cookies not persisting across cross-site requests",
    body: "The refreshToken cookie is set with SameSite=None and Secure=true, but Chrome blocks it because my frontend is on localhost:5173 and backend is on localhost:5000.",
    senderName: "Priya Sharma",
    senderEmail: "priya.sharma@infosys.com",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Python virtual environment collision with globally installed packages",
    body: "In the Python Mastery course, running `poetry install` attempts to link against Python 3.10 instead of 3.12 installed via pyenv. How can I isolate the path?",
    senderName: "Lucas Silva",
    senderEmail: "lucas.silva@uol.com.br",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Redux Toolkit: State mutation warning when pushing to array",
    body: "Getting an Immer error 'An immer producer returned a new value AND modified its original state'. Can you clarify line 44 in cartSlice.ts?",
    senderName: "Hannah Abbott",
    senderEmail: "hannah.abbott@alumni.edu",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "PostgreSQL: Deadlock detected while executing concurrent seed script",
    body: "When running the seed script with Promise.all, foreign key constraints cause deadlocks across user and session tables. Should transactions be sequential?",
    senderName: "Tariq Mansoor",
    senderEmail: "tariq.m@gmx.net",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Zod Schema: Optional string parsing empty string as invalid email",
    body: "My input schema fails when the email input is left blank because z.string().email().optional() treats '' as an invalid email string rather than undefined.",
    senderName: "Grace Hopper",
    senderEmail: "grace.h@cs.yale.edu",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "AWS S3 Upload: 403 Forbidden with pre-signed URL generation",
    body: "The PutObject command produces a pre-signed URL that returns 403 Forbidden when uploaded from browser client. CORS headers are already enabled on the S3 bucket.",
    senderName: "Ethan Walker",
    senderEmail: "ewalker@cloudcraft.io",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Git: Rebase conflict with detached HEAD after checkout",
    body: "I checked out a specific exercise tag and committed changes, now `git pull origin main` says I am in a detached HEAD state. How do I rescue my branch?",
    senderName: "Maya Lin",
    senderEmail: "maya.lin@berkeley.edu",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "TanStack Query v5: isPending vs isLoading behavior in React 19",
    body: "In TanStack Query v5, isPending is true on initial mount even before queryFn fires. Does this replace isLoading in skeleton fallbacks?",
    senderName: "Nico Becker",
    senderEmail: "nico.becker@berlin-tech.de",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "GraphQL Apollo Client: Cache normalized ID collision with composite keys",
    body: "Apollo InMemoryCache is overwriting course items that share the same numeric ID across different school tenants. How do I configure keyFields?",
    senderName: "Zara Phillips",
    senderEmail: "zara.p@fintech.co.uk",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "ESLint 9 Flat Config: Migration error with typescript-eslint plugin",
    body: "Upgrading eslint.config.js to flat format throws 'plugin:typescript-eslint/recommended not found'. How should languageOptions be structured?",
    senderName: "Oliver Queen",
    senderEmail: "oliver.queen@starling.com",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Bun: Segmentation fault when calling node:crypto in multi-threaded worker",
    body: "Running Bun v1.4 with worker_threads crashes when hashing passwords in parallel. Does Bun support Worker threads with native modules?",
    senderName: "Carlos Santana",
    senderEmail: "carlos.santana@devmx.org",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Vitest: In-source testing not stripping test blocks from Vite bundle",
    body: "When inspecting the production dist/assets bundle, import.meta.vitest blocks are still included, increasing the chunk size by 40KB.",
    senderName: "Aiden Scott",
    senderEmail: "aiden.scott@protonmail.com",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Kafka Consumer: Rebalance loop causing message processing starvation",
    body: "In the microservices module, Kafka consumers trigger a rebalance every 30 seconds because batch processing exceeds max.poll.interval.ms.",
    senderName: "Dmitri Ivanov",
    senderEmail: "dmitri.ivanov@yandex.ru",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Redis cache invalidation pattern for paginated search queries",
    body: "What is the recommended cache key strategy when searching tickets by arbitrary keywords and sorting filters in Redis?",
    senderName: "Amira Said",
    senderEmail: "amira.said@cairo-dev.eg",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Linux permissions: Permission denied when writing to /var/log/helpdesk",
    body: "Our systemd service running under the helpdesk user cannot write application logs to the target directory on Ubuntu 24.04.",
    senderName: "Ben Foster",
    senderEmail: "ben.foster@sysadmin.net",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Kubernetes Ingress: 502 Bad Gateway when routing to backend service",
    body: "Minikube ingress controller returns 502 Bad Gateway intermittently. The pod health check endpoint responds with 200 OK locally inside the cluster.",
    senderName: "Kavita Patel",
    senderEmail: "kavita.patel@tcs.in",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Playwright E2E: Flaky locator timeout on modal animation transition",
    body: "The delete modal test in users-management.spec.ts fails in CI when the dialog fade-in takes longer than 1000ms. What assertion handles CSS transitions gracefully?",
    senderName: "Fiona Gallagher",
    senderEmail: "fiona.g@qa-solutions.io",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "CORS preflight request fails with Missing Allowed Headers in Nginx",
    body: "When making an Axios PUT request with custom Authorization and X-Correlation-ID headers, the preflight OPTIONS request returns 405 Method Not Allowed.",
    senderName: "Julian Vance",
    senderEmail: "julian.vance@vancetech.com",
    category: TicketCategory.TECHNICAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },

  // 26-50: Refund Requests
  {
    subject: "Accidental purchase: Bought React 19 course twice",
    body: "I accidentally clicked the checkout button twice during network lag and my credit card was billed two times for Order #98421 and #98422. Please refund one.",
    senderName: "Brandon Lee",
    senderEmail: "brandon.lee@gmail.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Refund Request: Ultimate Docker course within 30-day money-back guarantee",
    body: "Hello Support, I purchased the Docker course 5 days ago (Order #77123). Due to unexpected job role changes, I won't have time to complete it. Requesting a full refund.",
    senderName: "Jessica Pearson",
    senderEmail: "jessica.pearson@law-ny.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Refund processed: Duplicate subscription charge on annual renewal",
    body: "My yearly All-Access subscription renewed on Sept 1, but my credit card statement shows two identical charges of $180. Please refund the duplicate.",
    senderName: "Robert Thorne",
    senderEmail: "rthorne@thorne-enterprises.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.HIGH,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Refund request - Purchased Python course instead of JavaScript Mastery",
    body: "I meant to buy the Complete JavaScript Mastery bundle, but accidentally selected Python for Beginners. Can you exchange the courses or refund me so I can re-order?",
    senderName: "Ananya Roy",
    senderEmail: "ananya.roy@outlook.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Unable to run project due to hardware constraints, requesting refund",
    body: "My old laptop does not support virtualization for the Docker and Kubernetes modules. I am within the 30-day refund window and would appreciate a refund.",
    senderName: "George Miller",
    senderEmail: "george.miller@student.ucla.edu",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Company reimbursed different course, refund personal purchase",
    body: "My employer agreed to pay for an enterprise team subscription. Can I get a refund for the personal license I purchased yesterday (Invoice #65412)?",
    senderName: "Claire Underwood",
    senderEmail: "claire.underwood@dc-gov.org",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.HIGH,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Refund request: Course content too advanced for my current level",
    body: "I thought the Advanced Microservices with Go course started from basics, but it expects senior distributed systems knowledge. Please refund my purchase.",
    senderName: "Samir Nasri",
    senderEmail: "samir.nasri@yahoo.fr",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Charged after cancelling free trial membership",
    body: "I cancelled my 7-day All Access free trial on day 5, but my card was charged $29 today. Please reverse the charge immediately.",
    senderName: "Rachel Zane",
    senderEmail: "rachel.zane@zane-legal.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Refund request: Currency conversion fee unexpectedly high",
    body: "I was billed in USD which resulted in excessive bank conversion fees in AUD. I would like a refund so I can pay through my company's US entity.",
    senderName: "Timothy Howard",
    senderEmail: "timothy.howard@sydney.com.au",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Refund request: Incompatible with my work schedule",
    body: "Purchased the Full Stack bundle last week, but got assigned to an emergency client project. Requesting refund under the 30-day satisfaction policy.",
    senderName: "Wendy Rhoades",
    senderEmail: "wendy.rhoades@axe-cap.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "VAT Tax exemption refund request for European business",
    body: "Our EU VAT number was not applied during checkout. We require a refund of the 20% VAT portion or a revised business invoice.",
    senderName: "Lars Van Der Bilt",
    senderEmail: "lars.v@amsterdam-tech.nl",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Partial refund request: Promotional discount code didn't apply",
    body: "I tried applying the BACKTOSCHOOL promo code for 30% off, but the checkout submitted at full price. Can you apply the discount retroactively as a partial refund?",
    senderName: "Megan Fox",
    senderEmail: "megan.fox@icloud.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Refund Request: Clean Code course - purchased under wrong student account",
    body: "I bought the course while logged into my personal email instead of my work email. Please refund Order #83912 so I can buy it from work.",
    senderName: "Harvey Specter",
    senderEmail: "harvey.specter@psl-law.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Course purchased accidentally by child on shared iPad",
    body: "My 9-year-old clicked buy on the Data Structures and Algorithms course while using my iPad. I haven't watched any videos. Please refund.",
    senderName: "Jennifer Aniston",
    senderEmail: "jen.aniston@hollywood.org",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.HIGH,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Dissatisfied with video player buffering - requesting refund",
    body: "The video player constantly stops to buffer even on a 500Mbps connection. Unable to watch comfortably. Requesting a full refund.",
    senderName: "Klaus Schmidt",
    senderEmail: "klaus.schmidt@munich.de",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Course already completed on Udemy, bought duplicate on Code With Mosh",
    body: "Realized halfway through chapter 1 that I already completed this exact course on Udemy last year. Please refund my order #44910.",
    senderName: "Sunita Reddy",
    senderEmail: "sunita.reddy@hyderabad.in",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Refund: Medical emergency preventing continuation of studies",
    body: "Due to an unexpected hospitalization I will be unable to study for several months. Requesting refund for order placed 3 days ago.",
    senderName: "Arthur Dent",
    senderEmail: "arthur.dent@earth.co.uk",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.HIGH,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Refund request: Course exercises rely on outdated third-party API",
    body: "The weather API used in lesson 6 has deprecated its free tier and requires credit card verification. I prefer not to use it. Please refund.",
    senderName: "Beatrix Kiddo",
    senderEmail: "beatrix@viper.org",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Refund request for monthly membership - forgotten renewal",
    body: "I intended to cancel my monthly membership after month 1 but forgot. The charge happened 6 hours ago. Please issue a refund.",
    senderName: "Walter White",
    senderEmail: "w.white@abq-chem.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Unauthorized charge on credit card for CodeWithMosh",
    body: "I noticed a charge of $149 from CodeWithMosh on my bank statement that I did not authorize. Please investigate and refund immediately.",
    senderName: "Jesse Pinkman",
    senderEmail: "jesse.p@albuquerque.net",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Refund request: Course language not suitable (thought it had Spanish audio)",
    body: "Hola, I thought the course had full Spanish voiceover, not just subtitles. It is difficult for me to follow English audio. Requesting refund.",
    senderName: "Mateo Fernandez",
    senderEmail: "mateo.f@buenosaires.ar",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Refund requested for inactive student account #3019",
    body: "Our student left our university program. We bought the license under our departmental credit card on Aug 28. Please process refund.",
    senderName: "Prof. Charles Xavier",
    senderEmail: "charles.xavier@mutant-academy.edu",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Bought course 2 hours before Black Friday sale launched",
    body: "I bought the All-Access pass at $299 right before the 50% Black Friday sale went live. Can you refund the difference or refund so I can re-buy?",
    senderName: "Peter Parker",
    senderEmail: "peter.parker@dailybugle.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Refund: Course requires Windows machine, I only have Linux",
    body: "The WPF/C# course requires Windows-specific Visual Studio tools which do not run under Linux Wine. Requesting refund under 30-day guarantee.",
    senderName: "Linus Torvaldsen",
    senderEmail: "linus.t@helsinki.fi",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Refund request - Course content covers Vue 2, need Vue 3 Composition API",
    body: "I bought the older Vue course by mistake looking for Vue 3 Composition API. Please refund order #58291.",
    senderName: "Dominic Toretto",
    senderEmail: "dom.toretto@family.com",
    category: TicketCategory.REFUND_REQUEST,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },

  // 51-75: General Questions
  {
    subject: "Do I get a verified certificate of completion for LinkedIn?",
    body: "Hi! If I complete the Full-Stack Developer roadmap, do I receive a verifiable certificate with a credential ID that I can add to LinkedIn?",
    senderName: "Serena Williams",
    senderEmail: "serena.williams@tennis.org",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Are course videos available for offline download on mobile?",
    body: "I commute by subway with no cellular signal. Does the CodeWithMosh mobile web player support offline video caching or direct downloads?",
    senderName: "Kenji Sato",
    senderEmail: "kenji.sato@tokyo-subway.jp",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Prerequisites for Ultimate Next.js 15 course",
    body: "Do I need to be proficient in TypeScript and Tailwind before starting the Next.js 15 course, or is standard JavaScript knowledge sufficient?",
    senderName: "Laura Croft",
    senderEmail: "laura.croft@adventures.co.uk",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Inquiry about team/enterprise corporate discounts for 15 engineers",
    body: "We are looking to onboard 15 junior developers onto Mosh's courses. Do you offer corporate group licensing or volume discounts?",
    senderName: "Natasha Romanoff",
    senderEmail: "natasha.r@avengers-tech.com",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Lifetime access clarification on All-Access Annual vs Single Course",
    body: "If I purchase an individual course, do I get lifetime access with future updates, or does access expire after 12 months?",
    senderName: "Bruce Banner",
    senderEmail: "bruce.banner@gamma-labs.org",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Are there closed captions or subtitles available in Japanese?",
    body: "I am a Japanese student and want to know if Japanese subtitles are available for the React and Node.js courses.",
    senderName: "Aoi Miyazaki",
    senderEmail: "aoi.m@shibuya-dev.jp",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Recommended learning path for backend engineering transition",
    body: "I am a frontend developer with 3 years of React experience wanting to transition to fullstack. Which sequence of courses does Mosh recommend?",
    senderName: "Tony Stark",
    senderEmail: "tony@starkindustries.com",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Can I get an educational invoice for college reimbursement?",
    body: "My university department needs an official invoice with university name and tax ID listed. How can I generate this from my receipt?",
    senderName: "Hermione Granger",
    senderEmail: "hermione.g@ministry-magic.gov.uk",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "How often is the React course updated with newer major versions?",
    body: "Now that React 19 is officially stable, will the React 18 course receive supplementary lectures on Server Actions and useActionState?",
    senderName: "Luke Skywalker",
    senderEmail: "luke@rebel-alliance.org",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Discord community invite link expired or invalid",
    body: "The invite link in chapter 1 to join the student Discord community says 'Invite Invalid or Expired'. Can you provide a fresh link?",
    senderName: "Diana Prince",
    senderEmail: "diana.prince@themyscira.gov",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Difference between Ultimate C# Masterclass part 1 and part 2",
    body: "Does Part 1 cover object oriented programming or is that in Part 2? Looking to brush up specifically on delegates and LINQ.",
    senderName: "Steve Rogers",
    senderEmail: "steve.rogers@brooklyn.org",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Can I share my account with my brother in the same household?",
    body: "My brother and I both want to learn web development. Is it against Terms of Service if we share the same login on our home computer?",
    senderName: "Thor Odinson",
    senderEmail: "thor@asgard.realm",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Student discount policy for university students outside the US",
    body: "Does CodeWithMosh offer student discounts for undergraduate computer science students in India or developing countries via GitHub Student Pack?",
    senderName: "Rajesh Koothrappali",
    senderEmail: "rajesh.k@caltech.edu",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Course code repository link on GitHub throwing 404",
    body: "The repository link in the lecture notes for lesson 14 points to github.com/mosh-hamedani/react-course-demo which returns a 404 page.",
    senderName: "Sheldon Cooper",
    senderEmail: "sheldon.cooper@caltech.edu",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.HIGH,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Is there a certificate renewal or expiration date?",
    body: "Once I earn my TypeScript certificate, does it remain valid indefinitely or do I need to re-take tests every year?",
    senderName: "Leonard Hofstadter",
    senderEmail: "leonard.h@caltech.edu",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "How do I change the name printed on my course completion certificate?",
    body: "My certificate printed my display nickname instead of my legal name. I need my legal name for my employer's professional development audit.",
    senderName: "Howard Wolowitz",
    senderEmail: "howard.w@nasa.gov",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Payment options: Can I pay with PayPal or Bank Wire Transfer?",
    body: "My country does not support Stripe credit card processing. Do you accept PayPal or direct IBAN wire transfer for the All-Access pass?",
    senderName: "Penny Teller",
    senderEmail: "penny.teller@cheesecake.com",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Course roadmap for DevOps engineering in 2026",
    body: "I have taken Docker and Linux. What courses should I take next to prepare for a Cloud Infrastructure role on AWS/GCP?",
    senderName: "Bernadette Rostenkowski",
    senderEmail: "bernadette.r@pharma-corp.com",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Video speed adjustment on mobile Safari iOS 18",
    body: "On iPhone Safari, playback speed reset to 1x every time a new video auto-plays. Is there a setting to lock playback speed at 1.5x?",
    senderName: "Amy Farrah Fowler",
    senderEmail: "amy.fowler@neuroscience.edu",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Do courses come with capstone projects suitable for a resume portfolio?",
    body: "I am building my junior developer portfolio. Can I deploy the course projects to Vercel/Render and showcase the code on my public GitHub?",
    senderName: "Stuart Bloom",
    senderEmail: "stuart.bloom@comicbook.com",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Purchasing gift access for a friend who is graduating",
    body: "Can I buy the Ultimate React Course as a gift card or gift code that I can send to a friend's email address on their graduation day?",
    senderName: "Emily Thorne",
    senderEmail: "emily.thorne@hamptons.org",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Are there interactive coding exercises or quizzes in the browser?",
    body: "Does CodeWithMosh use an in-browser code editor or are all exercises done locally in VS Code with provided source starter files?",
    senderName: "Barry Allen",
    senderEmail: "barry.allen@ccpd.gov",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "When will the System Design Interview course be released?",
    body: "I saw Mosh mention a dedicated System Design Interview preparation course in a recent YouTube video. What is the expected release timeframe?",
    senderName: "Iris West",
    senderEmail: "iris.west@centralcityherald.com",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Can I pause my All-Access monthly subscription for 2 months?",
    body: "I have exams coming up and won't be studying for 2 months. Can I pause billing temporarily without losing my course progress history?",
    senderName: "Cisco Ramon",
    senderEmail: "cisco.ramon@star-labs.com",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Updating account email address from old student email to personal",
    body: "My university is deactivating my @alumni.edu email account next month. How do I transfer my course licenses to my personal Gmail?",
    senderName: "Caitlin Snow",
    senderEmail: "caitlin.snow@star-labs.com",
    category: TicketCategory.GENERAL_QUESTION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.CLOSED,
  },

  // 76-100: Uncategorized & Miscellaneous
  {
    subject: "Thank you Mosh! Landed my first Senior React Developer role!",
    body: "Just wanted to say a huge thank you to Mosh and the team. After studying the React, TypeScript, and Design Patterns courses, I got an offer at Spotify!",
    senderName: "Miles Morales",
    senderEmail: "miles.morales@brooklyn-visions.edu",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Typo found in slide 14 of Lesson 8 (Section: Inheritance)",
    body: "Found a minor spelling error on slide 14: 'polymorphisim' instead of 'polymorphism'. Thought I'd let the team know for future slide updates.",
    senderName: "Gwen Stacy",
    senderEmail: "gwen.stacy@empire-state.edu",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Urgent: Account locked after multiple failed login attempts",
    body: "I forgot my password and attempted it several times. Now it says 'Account temporarily locked due to security policy'. Please unlock my account.",
    senderName: "Norman Osborn",
    senderEmail: "norman.osborn@oscorp.com",
    category: null,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Suggestion for a new course: Building AI Agents with LangChain and Next.js",
    body: "Would love to see a comprehensive course on LLM orchestration, RAG architectures, and AI agent workflows using TypeScript and LangGraph.",
    senderName: "Otto Octavius",
    senderEmail: "otto.octavius@fusion-research.org",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Partnership and sponsorship inquiry for European Tech Conference 2026",
    body: "We are organizing the largest European developer conference in Berlin this October. We would love to discuss a sponsorship or keynote opportunity with Mosh.",
    senderName: "Helena Bonham",
    senderEmail: "helena.b@berlin-tech-conf.eu",
    category: null,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Missing video file in downloadable assets ZIP for chapter 11",
    body: "The supplementary assets ZIP archive for chapter 11 is missing the database seed SQL file referenced in the video at minute 04:22.",
    senderName: "Arthur Curry",
    senderEmail: "arthur.curry@atlantis-ocean.org",
    category: null,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Feedback on the new course platform UI and dark mode styling",
    body: "The new UI is super clean! One minor issue: the contrast of code snippets in dark mode could be slightly higher for better readability on OLED screens.",
    senderName: "Victor Stone",
    senderEmail: "victor.stone@s-labs.org",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Security vulnerability report: Exposed Git folder on staging subdomain",
    body: "I noticed the staging test domain test.codewithmosh.com returned a 200 OK for .git/HEAD. Please restrict web server access to dotfiles.",
    senderName: "Elliot Alderson",
    senderEmail: "fsociety@proton.me",
    category: null,
    priority: TicketPriority.HIGH,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Podcasting interview invitation for 'The Full Stack Journey'",
    body: "Hi Mosh! I host a weekly developer podcast with 80k listeners. Would love to have you on as a guest to discuss the evolution of TypeScript and modern web tech.",
    senderName: "Lex Luthor",
    senderEmail: "lex@lexcorp.global",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Inquiry about translating course transcripts to Portuguese",
    body: "We run a non-profit coding bootcamp in Brazil and would love permission to translate video captions to Brazilian Portuguese to help underprivileged youth learn.",
    senderName: "Gabriela Santos",
    senderEmail: "gabriela.s@ong-brasil.org.br",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Two-Factor Authentication (2FA) SMS not arriving",
    body: "I am trying to log in but the 6-digit SMS verification code never reaches my mobile phone on country code +44. Can you reset my 2FA?",
    senderName: "Sherlock Holmes",
    senderEmail: "sherlock@221b-baker.co.uk",
    category: null,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Requesting recommendation letter for Canadian Express Entry PR visa",
    body: "I have completed 8 courses and your microservices program helped me land an engineering job. Would Mosh be open to confirming my completion for immigration?",
    senderName: "John Watson",
    senderEmail: "john.watson@nhs.uk",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Dark mode toggle causing white flash on initial page load",
    body: "When navigating between lessons, the screen flashes white before the theme hook activates the dark mode class on html tag.",
    senderName: "Moriarty Jim",
    senderEmail: "jim.m@criminal-mind.org",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Billing statement request with custom company address for accounting",
    body: "Our accounts department requires our full tax registration address printed on invoice #91023 to release payment reimbursement.",
    senderName: "Mycroft Holmes",
    senderEmail: "mycroft@cabinet-office.gov.uk",
    category: null,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Accessibility issue: Screen reader skipping code block line numbers",
    body: "Using NVDA on Windows, the code block reader is voicing line numbers as part of the code statements. Can aria-hidden be added to line numbers?",
    senderName: "Matt Murdock",
    senderEmail: "matt.murdock@hellskitchen.org",
    category: null,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Course recommendation for a high school computer science teacher",
    body: "I teach 11th grade AP Computer Science. Which course would be most engaging for high school students learning programming fundamentals?",
    senderName: "Foggy Nelson",
    senderEmail: "foggy.nelson@law-partner.com",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Cannot download invoice PDF from receipt page (ERR_INVALID_HTTP_RESPONSE)",
    body: "Clicking 'Download PDF' on invoice page #88391 results in a browser network error. Can you email me the PDF invoice directly?",
    senderName: "Karen Page",
    senderEmail: "karen.page@ny-bulletin.com",
    category: null,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Inquiry about bulk licenses for military veterans non-profit transition program",
    body: "We provide software training for transitioning military veterans. Do you have non-profit educational grants or licensing assistance?",
    senderName: "Frank Castle",
    senderEmail: "frank.castle@vets-code.org",
    category: null,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Notification: Unhandled exception in user webhook callback endpoint",
    body: "Our custom webhook receiver received an empty payload from event 'ticket.resolved' on ticket #420. Is the schema documented anywhere?",
    senderName: "Din Djarin",
    senderEmail: "mando@mandalorian.guild",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Account recovery: lost access to authenticator app on broken phone",
    body: "My phone was dropped and completely broken. I have no backup codes for Google Authenticator. How do I verify my identity to regain access?",
    senderName: "Grogu",
    senderEmail: "grogu@jedi-temple.org",
    category: null,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Course recommendation for preparing for AWS Certified Solutions Architect",
    body: "Does the Docker & Kubernetes bundle cover enough cloud container orchestration to prepare for AWS ECS and EKS exam domains?",
    senderName: "Boba Fett",
    senderEmail: "boba.fett@tatooine.palace",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
  {
    subject: "Question about enterprise SSO (SAML 2.0 / Okta) integration",
    body: "We want our 50 developers to sign in using Okta SSO instead of individual email/password accounts. Does CodeWithMosh support SAML SSO?",
    senderName: "Ahsoka Tano",
    senderEmail: "ahsoka.tano@fulcrum.net",
    category: null,
    priority: TicketPriority.HIGH,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Bug report: Video playback state losing progress when switching tabs",
    body: "If I switch browser tabs for 10 minutes, returning to the video resets the timestamp back to the beginning instead of resuming where I left off.",
    senderName: "Obi-Wan Kenobi",
    senderEmail: "ben.kenobi@high-ground.org",
    category: null,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.OPEN,
  },
  {
    subject: "Requesting certificate reissue due to legal marriage surname change",
    body: "I recently changed my legal surname after getting married. Can my 3 completed certificates be re-issued with my new surname?",
    senderName: "Padme Amidala",
    senderEmail: "padme.amidala@naboo.senate.gov",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.CLOSED,
  },
  {
    subject: "Feature request: Keyboard shortcut navigation for next/previous lecture",
    body: "It would be great to have keyboard shortcuts like Shift + N for next video and Shift + P for previous video to enable hands-free keyboard navigation.",
    senderName: "Anakin Skywalker",
    senderEmail: "anakin.skywalker@coruscant-pilot.org",
    category: null,
    priority: TicketPriority.LOW,
    status: TicketStatus.RESOLVED,
  },
];

async function main() {
  console.log(`🚀 Starting generation of 100 diverse, realistic tickets...`);

  const now = Date.now();
  // Spread tickets over the last 45 days (45 * 24 * 60 * 60 * 1000 ms)
  const totalTimespanMs = 45 * 24 * 60 * 60 * 1000;
  const timeStepMs = Math.floor(totalTimespanMs / rawTickets.length);

  const ticketsToCreate = rawTickets.map((t, idx) => {
    // Stagger dates from oldest to newest:
    // idx 0 is oldest (45 days ago), idx 99 is newest (minutes ago)
    const ticketTimeMs = now - totalTimespanMs + (idx * timeStepMs) + Math.floor(Math.random() * (timeStepMs * 0.5));
    const createdAt = new Date(ticketTimeMs);

    return {
      ...t,
      createdAt,
      updatedAt: createdAt,
    };
  });

  // Batch insert into Prisma
  let createdCount = 0;
  for (const ticket of ticketsToCreate) {
    await prisma.ticket.create({
      data: ticket,
    });
    createdCount++;
  }

  console.log(`✅ Successfully seeded ${createdCount} diverse tickets into PostgreSQL database!`);

  // Quick stats breakdown
  const total = await prisma.ticket.count();
  const open = await prisma.ticket.count({ where: { status: TicketStatus.OPEN } });
  const resolved = await prisma.ticket.count({ where: { status: TicketStatus.RESOLVED } });
  const closed = await prisma.ticket.count({ where: { status: TicketStatus.CLOSED } });
  const tech = await prisma.ticket.count({ where: { category: TicketCategory.TECHNICAL_QUESTION } });
  const refund = await prisma.ticket.count({ where: { category: TicketCategory.REFUND_REQUEST } });
  const general = await prisma.ticket.count({ where: { category: TicketCategory.GENERAL_QUESTION } });
  const uncat = await prisma.ticket.count({ where: { category: null } });

  console.log(`\n📊 Database Tickets Summary:`);
  console.log(`- Total tickets: ${total}`);
  console.log(`- Status: OPEN=${open}, RESOLVED=${resolved}, CLOSED=${closed}`);
  console.log(`- Categories: TECHNICAL=${tech}, REFUND=${refund}, GENERAL=${general}, UNCATEGORIZED=${uncat}`);
}

main()
  .catch((err) => {
    console.error("❌ Failed to seed tickets:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
