import { describe, it, expect, mock } from "bun:test";
import { TicketServiceError } from "../ticket.service";
import prisma from "../../../prisma";

let mockGenerateText = mock(async (_options: any) => ({
  text: "Thank you for reaching out. We have resolved the issue.",
}));

mock.module("ai", () => ({
  generateText: (options: any) => mockGenerateText(options),
}));

// Import ticketService after mock.module
const { ticketService } = await import("../ticket.service");

describe("ticketService.polishReply", () => {
  it("throws a TicketServiceError when draft text is empty", async () => {
    expect(ticketService.polishReply(null, "")).rejects.toThrow(TicketServiceError);
    expect(ticketService.polishReply(null, "   ")).rejects.toThrow("Draft reply text is required");
  });

  it("calls generateText with gpt-5.6-luna model and returns polished text", async () => {
    let capturedOptions: any = null;
    mockGenerateText = mock(async (options: any) => {
      capturedOptions = options;
      return {
        text: "Thank you for reaching out. We have resolved the issue.",
      };
    });

    const result = await ticketService.polishReply(null, "fixed the issue thanks");
    expect(result).toBe("Thank you for reaching out. We have resolved the issue.");
    expect(capturedOptions).toBeDefined();
    expect(capturedOptions.prompt).toContain("fixed the issue thanks");
    expect(capturedOptions.system).toContain("customer support");
  });

  it("includes ticket subject and body context in the prompt if ticketId exists", async () => {
    let capturedOptions: any = null;
    mockGenerateText = mock(async (options: any) => {
      capturedOptions = options;
      return {
        text: "Hello, here is the polished response.",
      };
    });

    const originalFindUnique = prisma.ticket.findUnique;
    (prisma.ticket as any).findUnique = mock(async () => ({
      subject: "Login failing on iOS",
      body: "I cannot log in with error 401",
    }));

    try {
      const result = await ticketService.polishReply(999, "try resetting your password");
      expect(result).toBe("Hello, here is the polished response.");
      expect(capturedOptions.prompt).toContain("Login failing on iOS");
      expect(capturedOptions.prompt).toContain("I cannot log in with error 401");
      expect(capturedOptions.prompt).toContain("try resetting your password");
    } finally {
      (prisma.ticket as any).findUnique = originalFindUnique;
    }
  });

  it("includes agent name in system prompt and appends sign-off when omitted by model", async () => {
    let capturedOptions: any = null;
    mockGenerateText = mock(async (options: any) => {
      capturedOptions = options;
      return {
        text: "Thank you for contacting us. Your refund has been approved.",
      };
    });

    const result = await ticketService.polishReply(null, "refund approved", "Agent Bob");
    expect(result).toBe(
      "Thank you for contacting us. Your refund has been approved.\n\nRegards,\nAgent Bob"
    );
    expect(capturedOptions.system).toContain("Regards,\nAgent Bob");
    expect(capturedOptions.prompt).toContain("Agent Name: Agent Bob");
  });

  it("preserves sign-off with agent name when already generated by model", async () => {
    mockGenerateText = mock(async () => ({
      text: "We have resolved the issue.\n\nRegards,\nAgent Bob",
    }));

    const result = await ticketService.polishReply(null, "fixed it", "Agent Bob");
    expect(result).toBe("We have resolved the issue.\n\nRegards,\nAgent Bob");
  });

  it("includes customer greeting Dear <cust_first_name>, and agent sign-off in polish reply", async () => {
    let capturedOptions: any = null;
    mockGenerateText = mock(async (options: any) => {
      capturedOptions = options;
      return {
        text: "We have updated your account permissions as requested.",
      };
    });

    const result = await ticketService.polishReply(
      null,
      "updated your permissions",
      "Sarah Connor",
      "John Doe"
    );

    expect(result).toBe(
      "Dear John,\n\nWe have updated your account permissions as requested.\n\nRegards,\nSarah Connor"
    );
    expect(capturedOptions.system).toContain("Dear John,");
    expect(capturedOptions.system).toContain("Regards,\nSarah Connor");
    expect(capturedOptions.prompt).toContain("Customer First Name: John");
    expect(capturedOptions.prompt).toContain("Agent Name: Sarah Connor");
  });

  it("extracts customer name from ticket record when not provided in arguments", async () => {
    mockGenerateText = mock(async () => ({
      text: "We have processed your refund.",
    }));

    const originalFindUnique = prisma.ticket.findUnique;
    (prisma.ticket as any).findUnique = mock(async () => ({
      subject: "Refund question",
      body: "Need refund for course",
      senderName: "Alice Wonderland",
    }));

    try {
      const result = await ticketService.polishReply(42, "refund done", "Agent Smith");
      expect(result).toBe(
        "Dear Alice,\n\nWe have processed your refund.\n\nRegards,\nAgent Smith"
      );
    } finally {
      (prisma.ticket as any).findUnique = originalFindUnique;
    }
  });

  it("normalizes an informal opening greeting to Dear <cust_first_name>,", async () => {
    mockGenerateText = mock(async () => ({
      text: "Hi John,\n\nWe have reset your account credentials.",
    }));

    const result = await ticketService.polishReply(
      null,
      "reset creds",
      "Agent Smith",
      "John Doe"
    );
    expect(result).toBe(
      "Dear John,\n\nWe have reset your account credentials.\n\nRegards,\nAgent Smith"
    );
  });

  it("throws TicketServiceError with 502 when generateText fails during polish", async () => {
    mockGenerateText = mock(async () => {
      throw new Error("OpenAI API rate limit exceeded");
    });

    try {
      await ticketService.polishReply(null, "draft reply text", "Agent");
      expect(true).toBe(false); // should not reach here
    } catch (err: any) {
      expect(err).toBeInstanceOf(TicketServiceError);
      expect(err.statusCode).toBe(502);
      expect(err.message).toContain("AI Polish failed: OpenAI API rate limit exceeded");
    }
  });
});

describe("ticketService.summarizeTicket", () => {
  it("throws 404 when ticket does not exist", async () => {
    const originalFindUnique = prisma.ticket.findUnique;
    (prisma.ticket as any).findUnique = mock(async () => null);

    try {
      expect(ticketService.summarizeTicket(999)).rejects.toThrow("Ticket not found");
    } finally {
      (prisma.ticket as any).findUnique = originalFindUnique;
    }
  });

  it("summarizes ticket and full conversation history using GPT-5.6 Luna", async () => {
    let capturedOptions: any = null;
    mockGenerateText = mock(async (options: any) => {
      capturedOptions = options;
      return {
        text: "**Core Issue**: Unable to deploy app.\n**Key Discussion**: Customer reported 500 error. Agent provided fix.\n**Current Status**: Resolved.",
      };
    });

    const originalFindUnique = prisma.ticket.findUnique;
    (prisma.ticket as any).findUnique = mock(async () => ({
      id: 42,
      subject: "Deployment Error",
      body: "Getting 500 error on deploy",
      senderName: "Dev Dave",
      senderEmail: "dave@example.com",
      priority: "HIGH",
      status: "RESOLVED",
      createdAt: new Date("2026-09-08T10:00:00Z"),
      replies: [
        {
          id: 1,
          senderType: "AGENT",
          body: "Please update your build command.",
          createdAt: new Date("2026-09-08T10:15:00Z"),
          user: { id: "u-1", name: "Agent Alice", role: "AGENT" },
        },
        {
          id: 2,
          senderType: "CUSTOMER",
          body: "That solved it, thank you!",
          createdAt: new Date("2026-09-08T10:30:00Z"),
          user: null,
        },
      ],
    }));

    try {
      const summary = await ticketService.summarizeTicket(42);
      expect(summary).toContain("Core Issue: Unable to deploy app.");
      expect(capturedOptions).toBeDefined();
      expect(capturedOptions.prompt).toContain("Deployment Error");
      expect(capturedOptions.prompt).toContain("Getting 500 error on deploy");
      expect(capturedOptions.prompt).toContain("Agent (Agent Alice)");
      expect(capturedOptions.prompt).toContain("Please update your build command.");
      expect(capturedOptions.prompt).toContain("Customer (Dev Dave)");
      expect(capturedOptions.prompt).toContain("That solved it, thank you!");
    } finally {
      (prisma.ticket as any).findUnique = originalFindUnique;
    }
  });

  it("summarizes ticket with no replies using fallback inquiry text", async () => {
    let capturedOptions: any = null;
    mockGenerateText = mock(async (options: any) => {
      capturedOptions = options;
      return {
        text: "Customer inquired about course discount. Status is Open.",
      };
    });

    const originalFindUnique = prisma.ticket.findUnique;
    (prisma.ticket as any).findUnique = mock(async () => ({
      id: 77,
      subject: "Discount Inquiry",
      body: "Is there a student discount available?",
      senderName: "Eve Student",
      senderEmail: "eve@example.com",
      priority: "LOW",
      status: "OPEN",
      createdAt: new Date("2026-09-08T11:00:00Z"),
      replies: [],
    }));

    try {
      const summary = await ticketService.summarizeTicket(77);
      expect(summary).toBe("Customer inquired about course discount. Status is Open.");
      expect(capturedOptions.prompt).toContain("(No replies in conversation yet.)");
    } finally {
      (prisma.ticket as any).findUnique = originalFindUnique;
    }
  });

  it("maps AI assistant author type correctly in conversation history", async () => {
    let capturedOptions: any = null;
    mockGenerateText = mock(async (options: any) => {
      capturedOptions = options;
      return {
        text: "AI provided initial troubleshooting steps. Customer acknowledged.",
      };
    });

    const originalFindUnique = prisma.ticket.findUnique;
    (prisma.ticket as any).findUnique = mock(async () => ({
      id: 88,
      subject: "Password Reset",
      body: "Cannot reset my password",
      senderName: "Frank User",
      senderEmail: "frank@example.com",
      priority: "MEDIUM",
      status: "OPEN",
      createdAt: new Date("2026-09-08T12:00:00Z"),
      replies: [
        {
          id: 1,
          senderType: "AI",
          body: "Please click the forgot password link.",
          createdAt: new Date("2026-09-08T12:01:00Z"),
          user: null,
        },
      ],
    }));

    try {
      const summary = await ticketService.summarizeTicket(88);
      expect(summary).toBe("AI provided initial troubleshooting steps. Customer acknowledged.");
      expect(capturedOptions.prompt).toContain("by AI Assistant");
      expect(capturedOptions.prompt).toContain("Please click the forgot password link.");
    } finally {
      (prisma.ticket as any).findUnique = originalFindUnique;
    }
  });

  it("throws TicketServiceError with 502 when generateText fails during summarize", async () => {
    mockGenerateText = mock(async () => {
      throw new Error("AI service connection timeout");
    });

    const originalFindUnique = prisma.ticket.findUnique;
    (prisma.ticket as any).findUnique = mock(async () => ({
      id: 99,
      subject: "Test Subject",
      body: "Test Body",
      senderName: "User",
      senderEmail: "user@example.com",
      priority: "LOW",
      status: "OPEN",
      createdAt: new Date(),
      replies: [],
    }));

    try {
      await ticketService.summarizeTicket(99);
      expect(true).toBe(false);
    } catch (err: any) {
      expect(err).toBeInstanceOf(TicketServiceError);
      expect(err.statusCode).toBe(502);
      expect(err.message).toContain("AI service connection timeout");
    } finally {
      (prisma.ticket as any).findUnique = originalFindUnique;
    }
  });
});
